/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as AudienciasRouteImport } from './routes/audiencias'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ContratosRouteImport } from './routes/contratos'
import { Route as DocumentosRouteImport } from './routes/documentos'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as TarefasRouteImport } from './routes/tarefas'
import { Route as ClientesIndexRouteImport } from './routes/clientes.index'
import { Route as ClientesIdRouteImport } from './routes/clientes.$id'
import { Route as ProcessosIndexRouteImport } from './routes/processos.index'
import { Route as ProcessosIdRouteImport } from './routes/processos.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const AudienciasRoute = AudienciasRouteImport.update({
  id: '/audiencias',
  path: '/audiencias',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ContratosRoute = ContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentosRoute = DocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const TarefasRoute = TarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIndexRoute = ClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIdRoute = ClientesIdRouteImport.update({
  id: '/clientes/$id',
  path: '/clientes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessosIndexRoute = ProcessosIndexRouteImport.update({
  id: '/processos/',
  path: '/processos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessosIdRoute = ProcessosIdRouteImport.update({
  id: '/processos/$id',
  path: '/processos/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/audiencias': typeof AudienciasRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contratos': typeof ContratosRoute
  '/documentos': typeof DocumentosRoute
  '/financeiro': typeof FinanceiroRoute
  '/login': typeof LoginRoute
  '/relatorios': typeof RelatoriosRoute
  '/tarefas': typeof TarefasRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/processos/$id': typeof ProcessosIdRoute
  '/clientes/': typeof ClientesIndexRoute
  '/processos/': typeof ProcessosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/audiencias': typeof AudienciasRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contratos': typeof ContratosRoute
  '/documentos': typeof DocumentosRoute
  '/financeiro': typeof FinanceiroRoute
  '/login': typeof LoginRoute
  '/relatorios': typeof RelatoriosRoute
  '/tarefas': typeof TarefasRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/processos/$id': typeof ProcessosIdRoute
  '/clientes': typeof ClientesIndexRoute
  '/processos': typeof ProcessosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/audiencias': typeof AudienciasRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contratos': typeof ContratosRoute
  '/documentos': typeof DocumentosRoute
  '/financeiro': typeof FinanceiroRoute
  '/login': typeof LoginRoute
  '/relatorios': typeof RelatoriosRoute
  '/tarefas': typeof TarefasRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/processos/$id': typeof ProcessosIdRoute
  '/clientes/': typeof ClientesIndexRoute
  '/processos/': typeof ProcessosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/audiencias'
    | '/configuracoes'
    | '/contratos'
    | '/documentos'
    | '/financeiro'
    | '/login'
    | '/relatorios'
    | '/tarefas'
    | '/clientes/$id'
    | '/processos/$id'
    | '/clientes/'
    | '/processos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/audiencias'
    | '/configuracoes'
    | '/contratos'
    | '/documentos'
    | '/financeiro'
    | '/login'
    | '/relatorios'
    | '/tarefas'
    | '/clientes/$id'
    | '/processos/$id'
    | '/clientes'
    | '/processos'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/audiencias'
    | '/configuracoes'
    | '/contratos'
    | '/documentos'
    | '/financeiro'
    | '/login'
    | '/relatorios'
    | '/tarefas'
    | '/clientes/$id'
    | '/processos/$id'
    | '/clientes/'
    | '/processos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  AudienciasRoute: typeof AudienciasRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ContratosRoute: typeof ContratosRoute
  DocumentosRoute: typeof DocumentosRoute
  FinanceiroRoute: typeof FinanceiroRoute
  LoginRoute: typeof LoginRoute
  RelatoriosRoute: typeof RelatoriosRoute
  TarefasRoute: typeof TarefasRoute
  ClientesIdRoute: typeof ClientesIdRoute
  ProcessosIdRoute: typeof ProcessosIdRoute
  ClientesIndexRoute: typeof ClientesIndexRoute
  ProcessosIndexRoute: typeof ProcessosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audiencias': {
      id: '/audiencias'
      path: '/audiencias'
      fullPath: '/audiencias'
      preLoaderRoute: typeof AudienciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contratos': {
      id: '/contratos'
      path: '/contratos'
      fullPath: '/contratos'
      preLoaderRoute: typeof ContratosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentos': {
      id: '/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof DocumentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarefas': {
      id: '/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof TarefasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/': {
      id: '/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof ClientesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/$id': {
      id: '/clientes/$id'
      path: '/clientes/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof ClientesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processos/': {
      id: '/processos/'
      path: '/processos'
      fullPath: '/processos/'
      preLoaderRoute: typeof ProcessosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processos/$id': {
      id: '/processos/$id'
      path: '/processos/$id'
      fullPath: '/processos/$id'
      preLoaderRoute: typeof ProcessosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  AudienciasRoute: AudienciasRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  ContratosRoute: ContratosRoute,
  DocumentosRoute: DocumentosRoute,
  FinanceiroRoute: FinanceiroRoute,
  LoginRoute: LoginRoute,
  RelatoriosRoute: RelatoriosRoute,
  TarefasRoute: TarefasRoute,
  ClientesIdRoute: ClientesIdRoute,
  ProcessosIdRoute: ProcessosIdRoute,
  ClientesIndexRoute: ClientesIndexRoute,
  ProcessosIndexRoute: ProcessosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
